name: CodeQL

on:
  push:
    branches: master
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Initialize CodeQL
      uses: Anthophila/codeql-action/codeql/init@master
      with:
        languages: javascript, java

#   This repo fails to use the Autobuild from CodeQL
#    - name: Autobuild
#      uses: Anthophila/codeql-action/codeql/autobuild@master
    
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Perform CodeQL Analysis
      uses: Anthophila/codeql-action/codeql/finish@master
